WIP:
  title: "^WIP:.*"
  mergeable: false

S:
  size-below: 10
M:
  size-above: 9
  size-below: 100
L:
  size-above: 100
  
Mobile:
  - package/mobile/*
  - package/mobile/**/*

iOS:
  - package/mobile/ios/*
  - package/mobile/ios/**/*

Android:
  - package/mobile/android/*
  - package/mobile/android/**/*

Web:
  - package/web/*
  - package/web/**/*

Desktop:
  - package/desktop/*
  - package/desktop/**/*

API:
  - package/api/*
  - package/api/**/*
