Mobile:
  - package/mobile/*
  - package/mobile/**/*

iOS:
  - package/mobile/ios/*
  - package/mobile/ios/**/*

Android:
  - package/mobile/android/*
  - package/mobile/android/**/*

Web:
  - package/web/*
  - package/web/**/*

Desktop:
  - package/desktop/*
  - package/desktop/**/*

API:
  - package/api/*
  - package/api/**/*

automation:
  - .github/*
  - .github/**/*