name: delete-merged-branch
on: pull_request

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: SvanBoxel/delete-merged-branch@v1.3.3
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'