name: Respost - write comment to new issue event
on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/respost@v0.1.0
        with:
          title: 'Posting new issue'
          body: 'Hello @${{ github.actor }}, thank you for posting an issue !'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
