name: Respost - Write comment to new comment event (using comvent)
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    # available commands to listen
    env:
      TEST_COMMAND: "^/test$"
      SYNC_COMMAND: "^/sync$"
      CLOSE_COMMAND: "^/close$"
    steps:
      # configure comvent to listen on declared command
      - uses: rytswd/comvent@v0.1.0
        id: test
        with:
          keyword: ${{ env.TEST_COMMAND }}

      - uses: rytswd/comvent@v0.1.0
        id: sync
        with:
          keyword: ${{ env.SYNC_COMMAND }}

      - uses: rytswd/comvent@v0.1.0
        id: close
        with:
          keyword: ${{ env.CLOSE_COMMAND }}

      # respost section to trigger action depending on used command

      - uses: rytswd/respost@v0.1.0
        with:
          title: Execute `/test` command
          body: "Hello, thank you for calling me with `${{ env.TEST_COMMAND }}` command!"
        if: steps.test.outputs.comvent != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: rytswd/respost@v0.1.0
        with:
          title: Execute `/sync` command
          body: "Issue will be synced with origin and set to proper state"
        if: steps.sync.outputs.comvent != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: rytswd/respost@v0.1.0
        with:
          title: Execute `/close` command
          body: "Issue will be closed"
        if: steps.close.outputs.comvent != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
