name: Respost - Write comment to new comment event (using comvent)
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      COMMAND: "/respost test$"
    steps:
      - uses: rytswd/comvent@v0.1.0
        id: comvent
        with:
          keyword: ${{ env.COMMAND }} # This is the regex string to match against

      - uses: rytswd/respost@v0.1.0
        with:
          title: Respost test
          body: "Hello, thank you for calling me with `${{ env.COMMAND }}` command!"
        if: ${{ env.COMVENT_OUTPUT }} != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMVENT_OUTPUT: ${{ steps.comvent.outputs.comvent }}

      - name: echo-variables
        run: |
          echo $COMMAND
          echo $COMVENT_OUTPUT
        env:
          COMVENT_OUTPUT: ${{ steps.comvent.outputs.comvent }}
