
name: Respost - write comment to new pull request event
on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/respost@v0.1.0
        with:
          title: 'Posting new pull request'
          body: 'Hello @${{ github.actor }}, thank you for posting an pull request !'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
